name: Azure Static Web Apps CI/CD

on:
 push:
   branches:
     - main
 pull_request:
   types: [opened, synchronize, reopened, closed]
   branches:
     - main

jobs:
 build_and_deploy_job:
   if: github.event_name == 'push' || (github.event_name == 'pull_request' && github.event.action != 'closed')
   runs-on: ubuntu-latest
   name: Build and Deploy Job
   permissions:
      id-token: write
      contents: read
   steps:
     - uses: actions/checkout@v3
       with:
         submodules: true
         lfs: false

     - name: Set up Python
       uses: actions/setup-python@v4
       with:
         python-version: '3.9'
     
     - name: Install Python dependencies
       run: |
         python -m pip install --upgrade pip
         pip install -r requirements.txt

     - name: Install ODBC Driver
       run: |
         sudo apt-get remove --purge --force-yes unixodbc-dev unixodbc odbcinst libodbcinst2 libodbc2 unixodbc-common
         curl https://packages.microsoft.com/keys/microsoft.asc | sudo apt-key add -
         curl https://packages.microsoft.com/config/ubuntu/20.04/prod.list | sudo tee /etc/apt/sources.list.d/mssql-release.list
         sudo apt-get update
         ACCEPT_EULA=Y sudo apt-get install -y --force-yes msodbcsql18
         sudo apt-get install -y --force-yes unixodbc-dev

     - name: Set up Node.js
       uses: actions/setup-node@v3
       with:
         node-version: '18'

     - name: Install And Build
       run: |
         npm install
         npm run build
         # Verify config files exist
         echo "Checking for critical config files..."
         if [ -f "staticwebapp.config.json" ]; then echo "✅ staticwebapp.config.json exists"; else echo "❌ staticwebapp.config.json missing"; exit 1; fi
         if [ -f "public/web.config" ]; then echo "✅ public/web.config exists"; else echo "❌ public/web.config missing"; exit 1; fi
         if [ -f "public/routes.json" ]; then echo "✅ public/routes.json exists"; else echo "❌ public/routes.json missing"; exit 1; fi
         if [ -f "public/_headers" ]; then echo "✅ public/_headers exists"; else echo "❌ public/_headers missing"; exit 1; fi
         # Copy config files to output directory to ensure they're deployed
         echo "Copying config files to output directory..."
         cp staticwebapp.config.json out/
         cp public/web.config out/
         cp public/routes.json out/
         cp public/_headers out/
         ls -la out/
       env:
         NEXT_PUBLIC_SUPABASE_URL: ${{ secrets.NEXT_PUBLIC_SUPABASE_URL }}
         NEXT_PUBLIC_SUPABASE_ANON_KEY: ${{ secrets.NEXT_PUBLIC_SUPABASE_ANON_KEY }}
         NEXT_PUBLIC_PDF_FUNCTION_URL: ${{ secrets.PDF_FUNCTION_URL || 'https://jhonboard-func.azurewebsites.net/api/generatepdf' }}

     - name: Install OIDC Client from Core Package
       run: npm install @actions/core@1.6.0 @actions/http-client

     - name: Get Id Token
       uses: actions/github-script@v6
       id: idtoken
       with:
          script: |
              const coredemo = require('@actions/core')
              return await coredemo.getIDToken()
          result-encoding: string

     - name: Build And Deploy
       id: builddeploy
       uses: Azure/static-web-apps-deploy@v1
       with:
         azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN_WHITE_RIVER_06F67820F }}
         action: "upload"
         app_location: "/"
         api_location: "" 
         output_location: "out"
         github_id_token: ${{ steps.idtoken.outputs.result }}
       env:
         NEXT_PUBLIC_SUPABASE_URL: ${{ secrets.NEXT_PUBLIC_SUPABASE_URL }}
         NEXT_PUBLIC_SUPABASE_ANON_KEY: ${{ secrets.NEXT_PUBLIC_SUPABASE_ANON_KEY }}
         NEXT_PUBLIC_PDF_FUNCTION_URL: ${{ secrets.PDF_FUNCTION_URL || 'https://jhonboard-func.azurewebsites.net/api/generatepdf' }}

 close_pull_request_job:
   if: github.event_name == 'pull_request' && github.event.action == 'closed'
   runs-on: ubuntu-latest
   name: Close Pull Request Job
   steps:
     - name: Close Pull Request
       id: closepullrequest
       uses: Azure/static-web-apps-deploy@v1
       with:
         azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN_WHITE_RIVER_06F67820F }}
         action: "close"